# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Ensemble_EN_Objective <- function(current_res, beta, lambda_sparsity, lambda_diversity, alpha,delta,b_0) {
    .Call(`_SplitReg_Ensemble_EN_Objective`, current_res, beta, lambda_sparsity, lambda_diversity, alpha,delta)
}

Prediction_Grid <- function(x_test, x_train, y_train, grid_betas) {
    .Call(`_SplitSvm_Prediction_Grid`, x_test, x_train, y_train, grid_betas)
}

Ensemble_EN_Grid <- function(x, y, which_lambda, lambdas_grid, lambda_fixed, alpha, num_groups, tolerance, max_iter,delta,b_0) {
    .Call(`_SplitSvm_Ensemble_EN_Grid`, x, y, which_lambda, lambdas_grid, lambda_fixed, alpha, num_groups, tolerance, max_iter,delta)
}

CV_Ensemble_EN <- function(x, y, which_lambda, lambdas_grid, lambda_fixed, alpha, num_groups, num_folds, tolerance, max_iter, num_threads,delta) {
    .Call(`_SplitSvm_CV_Ensemble_EN`, x, y, which_lambda, lambdas_grid, lambda_fixed, alpha, num_groups, num_folds, tolerance, max_iter, num_threads,delta)
}

Main_Ensemble_EN <- function(x_perm, y_perm, num_lambdas_sparsity, num_lambdas_diversity, alpha, num_groups, tolerance, max_iter, num_folds, num_threads,delta,lambda_sparsity) {
    .Call(`_SplitSvm_Main_Ensemble_EN`, x_perm, y_perm, num_lambdas_sparsity, num_lambdas_diversity, alpha, num_groups, tolerance, max_iter, num_folds, num_threads,delta,lambda_sparsity)
}

